move_action_node_robot1:
  ros__parameters:
    namespace: "robot1"
    action_cost_plugin: "plansys2_actions_cost::MoveActionCostDuration"
    
    specialized_arguments: ["?0"]
    "?0": ["robot1"]

    fluent_to_update: "duration_move"
    fluent_args: [0,1,2]
    update_fluent: True

    # move_duration: [0,1,2]
move_action_node_robot2:
  ros__parameters:
    namespace: "robot2"
    action_cost_plugin: "plansys2_actions_cost::MoveActionCostDuration"
    
    specialized_arguments: ["?0"]
    "?0": ["robot2"]
    fluent_to_update: "duration_move"
    fluent_args: [0,1,2]
    update_fluent: True


  
patrol_action_node_robot1:
  ros__parameters:
    namespace: "robot1"
    specialized_arguments: ["?0"]
    "?0": ["robot1"]

    fluent_to_update: "duration_patrol"
    fluent_args: [0,1]
    update_fluent: True

patrol_action_node_robot2:
  ros__parameters:
    namespace: "robot2"
    specialized_arguments: ["?0"]
    "?0": ["robot2"]
    # action_cost_plugin: "plansys2_actions_cost::MoveActionCostDuration"
    # fluent_to_update: "move_duration"
    # move_duration: [0,1,2]
    fluent_to_update: "duration_patrol"
    fluent_args: [0,1]
    update_fluent: True

clean_action_node_robot1:
  ros__parameters:
    namespace: "robot1"
    specialized_arguments: ["?0"]
    "?0": ["robot1"]

    action_cost_plugin: "plansys2_actions_cost::MoveThroughPosesActionCostDuration"
    fluent_to_update: "duration_clean"
    fluent_args: [0,1,2]
    update_fluent: True

clean_action_node_robot2:
  ros__parameters:
    namespace: "robot2"
    specialized_arguments: ["?0"]
    "?0": ["robot2"]

    action_cost_plugin: "plansys2_actions_cost::MoveThroughPosesActionCostDuration"
    fluent_to_update: "duration_clean"
    fluent_args: [0,1,2]
    update_fluent: True

attend_person_node_robot1:
  ros__parameters:
    namespace: "robot1"
    specialized_arguments: ["?0"]
    "?0": ["robot1"]

    action_cost_plugin: "plansys2_actions_cost::MoveActionCostDuration"
    fluent_to_update: "duration_attend_person"
    fluent_args: [0,2,3]
    update_fluent: True

attend_person_node_robot2:
  ros__parameters:
    namespace: "robot2"
    specialized_arguments: ["?0"]
    "?0": ["robot2"]

    action_cost_plugin: "plansys2_actions_cost::MoveActionCostDuration"
    fluent_to_update: "duration_attend_person"
    fluent_args: [0,2,3]
    update_fluent: True
