humans_scene_manager_node:
  ros__parameters:
    test: "test"
    people_groups: ["first_group_of_people","entrance_group", "room2"]

    first_group_of_people:
      - person_1
      - person_2
      - person_3
    entrance_group:
      - entrance_person_1
      - entrance_person_2
    room2:
      - room2_person_1
      - room2_person_2

    person_1: 
      reference_frame: "map"  
      sdf_file_path: "/home/kalman/projects/turtlebot_ws/src/multi_robot/models/human/casual_man.sdf"
      position: [0.0, 0.0, 0.0] # x y z
      orientation: [0.0, 0.0, 0.0, 1.0] # qx qy qz qw
    person_2: 
      reference_frame: "map"  
      sdf_file_path: "/home/kalman/projects/turtlebot_ws/src/multi_robot/models/human/elegant_man.sdf"
      position: [0.4, 0.4, 0.0] # x y z
      orientation: [ 0.0, 0.0, -0.7071068, 0.7071068 ] # qx qy qz qw
    person_3: 
      reference_frame: "map"  
      sdf_file_path: "/home/kalman/projects/turtlebot_ws/src/multi_robot/models/human/worker_man.sdf"
      position: [0.4, -0.3, 0.0] # x y z
      orientation: [0.0, 0.0, 0.7071068, 0.7071068 ] # qx qy qz qw
    entrance_person_1: 
      reference_frame: "map"  
      sdf_file_path: "/home/kalman/projects/turtlebot_ws/src/multi_robot/models/human/casual_man.sdf"
      position: [-0.7, -3.4, 0.0] # x y z
      orientation: [0.0, 0.0, -0.7071068, 0.7071068]
      # orientation: [ 0.0,0.0, -0.3826834, 0.9238795 ] # qx qy qz qw
    entrance_person_2: 
      reference_frame: "map"  
      sdf_file_path: "/home/kalman/projects/turtlebot_ws/src/multi_robot/models/human/elegant_man.sdf"
      position: [-0.9, -4.2, 0.0] # x y z
      orientation: [0.0, 0.0, 0.7071068, 0.7071068 ] # qx qy qz qw

     # orientation: [ 0.0, 0.0, -0.9238795, -0.3826834 ] # qx qy qz qw
    room2_person_1: 
      reference_frame: "map"  
      sdf_file_path: "/home/kalman/projects/turtlebot_ws/src/multi_robot/models/human/casual_man.sdf"
      position: [-3.34, 0.15, 0.0] # x y z
      orientation: [0.0, 0.0, 0.7071068, 0.7071068 ] # qx qy qz qw
    room2_person_2:
      reference_frame: "map"  
      sdf_file_path: "/home/kalman/projects/turtlebot_ws/src/multi_robot/models/human/elegant_man.sdf"
      position: [-3.44, 0.9, 0.0] # x y z
      orientation: [0.0, 0.0, -0.7071068, 0.7071068]
